# Generated by Django 5.0.7 on 2024-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('1', 'создана'), ('2', 'запущена'), ('3', 'завершена')], help_text='Выберите статус рассылки', max_length=100, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('1', 'раз в день'), ('2', 'раз в неделю'), ('3', 'раз в месяц')], help_text='Выберите периодичность рассылки', max_length=20, verbose_name='Периодичность рассылки'),
        ),
    ]
