# Generated by Django 5.0.7 on 2024-07-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_avatar_client_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comments',
            new_name='comment',
        ),
    ]
