# Generated by Django 5.0.7 on 2024-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_rename_comments_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], help_text='Выберите статус рассылки', max_length=100, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], help_text='Выберите периодичность рассылки', max_length=20, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(help_text='Напишите тему сообщения', max_length=200, verbose_name='Тема сообщения'),
        ),
    ]
