# Generated by Django 5.0.7 on 2024-08-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailinglog_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-send_at",),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="created_at",
            new_name="send_at",
        ),
    ]
