# Generated by Django 5.0.7 on 2024-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="send_at",
            field=models.DateTimeField(verbose_name="Введите дату создания рассылки"),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="sent_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Укажите время отправки рассылки",
                verbose_name="Время отправки рассылки",
            ),
        ),
    ]
