# Generated by Django 5.0.7 on 2024-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailing_send_at_alter_mailinglog_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="send_at",
            field=models.DateTimeField(verbose_name="Введите дату отправки рассылки"),
        ),
    ]
