# Generated by Django 5.0.7 on 2024-08-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_mailing_send_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-send_time",),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="send_at",
            new_name="send_time",
        ),
    ]
