# Generated by Django 5.0.7 on 2024-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0013_alter_mailing_mailing_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-first_send_time",),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="send_time",
        ),
        migrations.AddField(
            model_name="mailing",
            name="first_send_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату и время начала рассылки",
                null=True,
                verbose_name="Дата и время начала рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="last_send_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату и время окончания рассылки",
                null=True,
                verbose_name="Дата и время окончания рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Дата и время следующей отправки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_status",
            field=models.CharField(
                choices=[
                    ("CREATED", "создана"),
                    ("LAUNCHED", "запущена"),
                    ("COMPLETED", "завершена"),
                ],
                default="created",
                help_text="Выберите статус рассылки",
                max_length=100,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("DAILY", "раз в день"),
                    ("WEEKLY", "раз в неделю"),
                    ("MONTHLY", "раз в месяц"),
                ],
                help_text="Выберите периодичность рассылки",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="is_success",
            field=models.BooleanField(
                choices=[(True, "успешная отправка"), (False, "ошибка отправки")],
                default=False,
                verbose_name="Статус попытки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="sent_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время отправки рассылки"
            ),
        ),
    ]
