# Generated by Django 5.0.7 on 2024-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0014_alter_mailing_options_remove_mailing_send_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglog",
            name="is_success",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Статус попытки рассылки"
            ),
        ),
    ]
