# Generated by Django 5.0.7 on 2024-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0015_alter_mailinglog_is_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="mailing_status",
            field=models.CharField(
                choices=[
                    ("CREATED", "создана"),
                    ("LAUNCHED", "запущена"),
                    ("PAUSED", "в ожидании отправки"),
                    ("COMPLETED", "завершена"),
                ],
                default="created",
                help_text="Выберите статус рассылки",
                max_length=100,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
