# Generated by Django 4.2.2 on 2024-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0018_client_owner_mailinglog_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("-first_send_time",),
                "permissions": [("change_mailing_status", "Can change mailing status")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
